// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// MatrixVector
NumericVector MatrixVector(const NumericMatrix& matrix, const NumericVector& vector, const bool verbose);
RcppExport SEXP simGWAS_MatrixVector(SEXP matrixSEXP, SEXP vectorSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vector(vectorSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(MatrixVector(matrix, vector, verbose));
    return __result;
END_RCPP
}
// combinationRefs
NumericMatrix combinationRefs(const IntegerMatrix& x, const IntegerMatrix& cols, const IntegerMatrix& reference, const NumericVector& prop, int shiftSize, int threads, bool verbose);
RcppExport SEXP simGWAS_combinationRefs(SEXP xSEXP, SEXP colsSEXP, SEXP referenceSEXP, SEXP propSEXP, SEXP shiftSizeSEXP, SEXP threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type prop(propSEXP);
    Rcpp::traits::input_parameter< int >::type shiftSize(shiftSizeSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(combinationRefs(x, cols, reference, prop, shiftSize, threads, verbose));
    return __result;
END_RCPP
}
// combination2
IntegerMatrix combination2(IntegerMatrix x, IntegerMatrix cols);
RcppExport SEXP simGWAS_combination2(SEXP xSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type cols(colsSEXP);
    __result = Rcpp::wrap(combination2(x, cols));
    return __result;
END_RCPP
}
// wsumsq
double wsumsq(const NumericVector& xx, const NumericVector& yy, const NumericVector& ww);
RcppExport SEXP simGWAS_wsumsq(SEXP xxSEXP, SEXP yySEXP, SEXP wwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector& >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type yy(yySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ww(wwSEXP);
    __result = Rcpp::wrap(wsumsq(xx, yy, ww));
    return __result;
END_RCPP
}
