# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MatrixVector <- function(matrix, vector, verbose = FALSE) {
    .Call('simGWAS_MatrixVector', PACKAGE = 'simGWAS', matrix, vector, verbose)
}

combinationRefs <- function(x, cols, reference, prop, shiftSize = 2L, threads = -1L, verbose = FALSE) {
    .Call('simGWAS_combinationRefs', PACKAGE = 'simGWAS', x, cols, reference, prop, shiftSize, threads, verbose)
}

combination2 <- function(x, cols) {
    .Call('simGWAS_combination2', PACKAGE = 'simGWAS', x, cols)
}

wsumsq <- function(xx, yy, ww) {
    .Call('simGWAS_wsumsq', PACKAGE = 'simGWAS', xx, yy, ww)
}

